// <auto-generated />
using System;
using ComoEstamos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComoEstamos.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928204204_EhDividaObrigatorio")]
    partial class EhDividaObrigatorio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ComoEstamos.Data.Model.Carteira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_carteira");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dm_ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_criacao");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nm_carteira");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("tb_carteira");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_categoria");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dm_ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_criacao");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_usuario");

                    b.Property<byte[]>("Imagem")
                        .HasColumnType("BLOB")
                        .HasColumnName("img_categoria");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nm_categoria");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("tb_categoria");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_conta");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dm_ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_criacao");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_usuario");

                    b.Property<byte[]>("Imagem")
                        .HasColumnType("BLOB")
                        .HasColumnName("img_conta");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nm_conta");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("nr_saldo");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("tb_conta");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Credor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_credor");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dm_ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_criacao");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_usuario");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("BLOB")
                        .HasColumnName("img_logo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nm_credor");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT")
                        .HasColumnName("ds_observacoes");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("tb_credor");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Divida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_divida");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dm_ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_criacao");

                    b.Property<DateTime>("DataPrimeiroVencimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_primeiro_vencimento");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dia_vencimento");

                    b.Property<bool>("EhDivida")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dm_divida");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_categoria");

                    b.Property<int?>("IdConta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_conta");

                    b.Property<int?>("IdCredor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_credor");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nm_divida");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nr_parcelas");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("nr_valor");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdConta");

                    b.HasIndex("IdCredor");

                    b.HasIndex("IdUsuario");

                    b.ToTable("tb_divida", t =>
                        {
                            t.HasCheckConstraint("CK_tb_divida_dia_vencimento", "dia_vencimento >= 1 AND dia_vencimento <= 31");

                            t.HasCheckConstraint("CK_tb_divida_nr_valor", "CAST(nr_valor AS REAL) >= 0");
                        });
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Historico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_historico");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dm_ativo");

                    b.Property<decimal>("Cotacao")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("vl_cotacao");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_criacao");

                    b.Property<DateTime>("DataHistorico")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_historico");

                    b.Property<int>("IdInvestimento")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_investimento");

                    b.Property<string>("NomeInvestimento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nm_investimento");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("ds_observacao");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("nr_quantidade");

                    b.HasKey("Id");

                    b.HasIndex("IdInvestimento");

                    b.ToTable("tb_historico");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Investimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_investimento");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dm_ativo");

                    b.Property<decimal>("Cotacao")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("vl_cotacao");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_criacao");

                    b.Property<int>("IdCarteira")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_carteira");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nm_investimento");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("ds_observacao");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("nr_quantidade");

                    b.HasKey("Id");

                    b.HasIndex("IdCarteira");

                    b.ToTable("tb_investimento");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Operacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_operacao");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dm_ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_criacao");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_operacao");

                    b.Property<bool>("EhCompra")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dm_compra");

                    b.Property<int>("IdInvestimento")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_investimento");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("nr_quantidade");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("vl_operacao");

                    b.HasKey("Id");

                    b.HasIndex("IdInvestimento");

                    b.ToTable("tb_operacao");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_parcela");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dm_ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_criacao");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_pagamento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_vencimento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ds_parcela");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IdConta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_conta");

                    b.Property<int>("IdDivida")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_divida");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("nr_valor");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdConta");

                    b.HasIndex("IdDivida");

                    b.ToTable("tb_parcela");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_usuario");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dm_ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_criacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ds_email");

                    b.Property<byte[]>("Imagem")
                        .HasColumnType("BLOB")
                        .HasColumnName("img_usuario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nm_usuario");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("ds_senha");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "UQ_tb_usuario_ds_email")
                        .IsUnique();

                    b.ToTable("tb_usuario");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Carteira", b =>
                {
                    b.HasOne("ComoEstamos.Data.Model.Usuario", "Usuario")
                        .WithMany("Carteiras")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Categoria", b =>
                {
                    b.HasOne("ComoEstamos.Data.Model.Usuario", "Usuario")
                        .WithMany("Categorias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Conta", b =>
                {
                    b.HasOne("ComoEstamos.Data.Model.Usuario", "Usuario")
                        .WithMany("Contas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Credor", b =>
                {
                    b.HasOne("ComoEstamos.Data.Model.Usuario", "Usuario")
                        .WithMany("Credores")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Divida", b =>
                {
                    b.HasOne("ComoEstamos.Data.Model.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComoEstamos.Data.Model.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComoEstamos.Data.Model.Credor", "Credor")
                        .WithMany()
                        .HasForeignKey("IdCredor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComoEstamos.Data.Model.Usuario", "Usuario")
                        .WithMany("Dividas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Conta");

                    b.Navigation("Credor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Historico", b =>
                {
                    b.HasOne("ComoEstamos.Data.Model.Investimento", "Investimento")
                        .WithMany("Historicos")
                        .HasForeignKey("IdInvestimento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Investimento");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Investimento", b =>
                {
                    b.HasOne("ComoEstamos.Data.Model.Carteira", "Carteira")
                        .WithMany("Investimentos")
                        .HasForeignKey("IdCarteira")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carteira");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Operacao", b =>
                {
                    b.HasOne("ComoEstamos.Data.Model.Investimento", "Investimento")
                        .WithMany("Operacoes")
                        .HasForeignKey("IdInvestimento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Investimento");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Parcela", b =>
                {
                    b.HasOne("ComoEstamos.Data.Model.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComoEstamos.Data.Model.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComoEstamos.Data.Model.Divida", "Divida")
                        .WithMany("Parcelas")
                        .HasForeignKey("IdDivida")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Conta");

                    b.Navigation("Divida");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Carteira", b =>
                {
                    b.Navigation("Investimentos");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Divida", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Investimento", b =>
                {
                    b.Navigation("Historicos");

                    b.Navigation("Operacoes");
                });

            modelBuilder.Entity("ComoEstamos.Data.Model.Usuario", b =>
                {
                    b.Navigation("Carteiras");

                    b.Navigation("Categorias");

                    b.Navigation("Contas");

                    b.Navigation("Credores");

                    b.Navigation("Dividas");
                });
#pragma warning restore 612, 618
        }
    }
}
